"""210224-213956

Revision ID: 03fa21daf498
Revises: 
Create Date: 2021-02-24 15:39:57.860540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03fa21daf498'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_extra_info', sa.Column('national_id', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_extra_info', 'national_id')
    # ### end Alembic commands ###
