""" - Migrate Plan Date: 21/03/15-15:06:55

Revision ID: e0aaa81b0c11
Revises: ee2074d8fd2a
Create Date: 2021-03-15 09:06:56.172891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0aaa81b0c11'
down_revision = 'ee2074d8fd2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('emp_accepted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'emp_accepted')
    # ### end Alembic commands ###
