""" - Migrate Plan Date: 21/03/10-17:54:33

Revision ID: ee2074d8fd2a
Revises: e27d9f39499f
Create Date: 2021-03-10 11:54:34.136567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2074d8fd2a'
down_revision = 'e27d9f39499f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_id_document_types', sa.Column('enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog_id_document_types', 'enabled')
    # ### end Alembic commands ###
